/* automatically generated by rust-bindgen */

use crate::dep_types::*;
use crate::poppler::*;

pub type guint64 = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _PopplerMovie {
    _unused: [u8; 0],
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum PopplerMoviePlayMode {
    POPPLER_MOVIE_PLAY_MODE_ONCE = 0,
    POPPLER_MOVIE_PLAY_MODE_OPEN = 1,
    POPPLER_MOVIE_PLAY_MODE_REPEAT = 2,
    POPPLER_MOVIE_PLAY_MODE_PALINDROME = 3,
}
extern "C" {
    pub fn poppler_movie_get_type() -> GType;
}
extern "C" {
    pub fn poppler_movie_get_filename(poppler_movie: *mut PopplerMovie) -> *const gchar;
}
extern "C" {
    pub fn poppler_movie_need_poster(poppler_movie: *mut PopplerMovie) -> gboolean;
}
extern "C" {
    pub fn poppler_movie_show_controls(poppler_movie: *mut PopplerMovie) -> gboolean;
}
extern "C" {
    pub fn poppler_movie_get_play_mode(poppler_movie: *mut PopplerMovie) -> PopplerMoviePlayMode;
}
extern "C" {
    pub fn poppler_movie_is_synchronous(poppler_movie: *mut PopplerMovie) -> gboolean;
}
extern "C" {
    pub fn poppler_movie_get_volume(poppler_movie: *mut PopplerMovie) -> gdouble;
}
extern "C" {
    pub fn poppler_movie_get_rate(poppler_movie: *mut PopplerMovie) -> gdouble;
}
extern "C" {
    pub fn poppler_movie_get_rotation_angle(poppler_movie: *mut PopplerMovie) -> gushort;
}
extern "C" {
    pub fn poppler_movie_get_start(poppler_movie: *mut PopplerMovie) -> guint64;
}
extern "C" {
    pub fn poppler_movie_get_duration(poppler_movie: *mut PopplerMovie) -> guint64;
}
